version: "3.7"

services:
  app: &app_base
    build:
      context: .
      args:
        - RUBY_VERSION=2.7.2
        - NODE_VERSION=15.5.0
        - ALPINE_VERSION=3.12 # 余計なイメージのダウンロードを避けるため、ALPINEのバージョンをそろえたい場合は指定する
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0" # 最初はコマンド引数から rails new することで、プロジェクト作成前の rails s を上書きできる。
    environment:
      - DB_HOST=localhost # デフォルト値付きの環境変数
      - DB_DATABASE=app_local
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_PORT=3306
    volumes:
      - .:/app:cached # ホストへの反映の遅延を許容して高速化する
    volumes_from:
      - datastore
    ports:
      - "3000:3000"
    depends_on:
      - db

  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    volumes_from:
      - datastore
    expose:
      - "3036"
    depends_on:
      - app

  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=app_local
      - MYSQL_USER=app_root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306" # DBクライアント接続用にホストにも公開しておく
    volumes_from:
      - datastore

  datastore:
    image: alpine:3.12
    volumes:
      - mysql-data:/var/lib/mysql
      - vendor-bundle:/app/vendor/bundle
      - bundle:/app/.bundle
      - node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  vendor-bundle:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
