version: "3.7"

services:
  app: &app_base
    build: .
    entrypoint: ["entrypoint.sh"] # bundler と yarn のパッケージを実行時にインストールする
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0" # 最初はコマンド引数から rails new することで、プロジェクト作成前の rails s を上書きできる。
    environment:
      - DB_HOST=${DB_HOST:-localhost} # デフォルト値付きの環境変数
      - DB_DATABASE=${DB_DATABASE:-app}
      - DB_USER=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_PORT=${DB_PORT:-3306}
    volumes:
      - .:/app:cached # ホストへの反映の遅延を許容して高速化する
    volumes_from:
      - datastore
    ports:
      - "3000:3000"
    depends_on:
      - db

  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    volumes_from:
      - datastore
    ports:
      - "3035:3035"
    depends_on:
      - app

  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_USER=${DB_USERNAME:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
    ports:
      - "${DB_PORT}:3306"
    volumes_from:
      - datastore

  datastore:
    image: alpine:3.12
    volumes:
      - mysql-data:/var/lib/mysql
      - vendor-bundle:/app/vendor/bundle
      - dotbundle:/app/.bundle
      - node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  vendor-bundle:
    driver: local
  dotbundle:
    driver: local
  node_modules:
    driver: local
